apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-scripts-configmap.yaml
  - postgres-backup-cronjob.yaml
  - neo4j-backup-cronjob.yaml
  - qdrant-backup-cronjob.yaml
  - opensearch-backup-cronjob.yaml
  - minio-versioning-job.yaml
